#pragma once

#include "driver/gpio.h"
#include "driver/uart.h"

#define BOARD_GPIO_NC ((gpio_num_t)-1)

#define BOARD_UART_DYP UART_NUM_1
#define BOARD_UART_SCALE UART_NUM_2
#define BOARD_UART_BIO UART_NUM_0

#define BOARD_DYP_BAUDRATE 9600
#define BOARD_SCALE_BAUDRATE 9600
#define BOARD_BIO_BAUDRATE 9600

// TODO: ajustar conforme a placa final.
#define BOARD_PIN_DYP_TX BOARD_GPIO_NC
#define BOARD_PIN_DYP_RX BOARD_GPIO_NC

#define BOARD_PIN_SCALE_TX BOARD_GPIO_NC
#define BOARD_PIN_SCALE_RX BOARD_GPIO_NC

#define BOARD_PIN_BIO_TX BOARD_GPIO_NC
#define BOARD_PIN_BIO_RX BOARD_GPIO_NC

#define BOARD_PIN_DIP_ORIENTATION BOARD_GPIO_NC
#define BOARD_PIN_DIP_MODE_HEIGHT BOARD_GPIO_NC
#define BOARD_PIN_DIP_SCALE_DIV100 BOARD_GPIO_NC

#define BOARD_PIN_NEON_PWM BOARD_GPIO_NC
#define BOARD_PIN_RGB_DATA BOARD_GPIO_NC

#define BOARD_LED_STRIP_COUNT 300